name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        id: run_tests
        run: pytest --maxfail=1 --disable-warnings


      - name: Create revert branch if tests fail
        if: failure()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b revert-${{ github.sha }}
          git revert -m 1 ${{ github.sha }}
          git push origin revert-${{ github.sha }}

      - name: Create pull request to revert commit
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Revert failed commit ${{ github.sha }}" \
            --body "Tests failed, automatically suggesting a revert." \
            --base main \
            --head revert-${{ github.sha }}
